### ISSUE TITLE
fatal  error C1083: Cannot open include file: 'pthread.h': No such file or directory

### ISSUE THREAD

**Issue by Thundros** [NVlabs/instant-ngp#1098]
I am trying to compile this but for some reason I am getting the following error log in CMake

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: C:/ngp/bin/CMakeFiles/CMakeScratch/TryCompile-o6idkg

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_b804f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.3.1+2badb37d1 for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64

  src.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CMAKE_HAVE_LIBC_PTHREAD /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b804f.dir\Debug\\" /Fd"cmTC_b804f.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-o6idkg\src.c"

C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-o6idkg\src.c(1,10): fatal  error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-o6idkg\cmTC_b804f.vcxproj]

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: C:/ngp/bin/CMakeFiles/CMakeScratch/TryCompile-5gbqgq

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_3b337.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.3.1+2badb37d1 for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64

  CheckFunctionExists.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3b337.dir\Debug\\" /Fd"cmTC_3b337.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-5gbqgq\CheckFunctionExists.c"

LINK : fatal error LNK1104: cannot open file 'pthreads.lib' [C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-5gbqgq\cmTC_3b337.vcxproj]

Determining if the function pthread_create exists in the pthread failed with the following output:
Change Dir: C:/ngp/bin/CMakeFiles/CMakeScratch/TryCompile-3rh8on

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_729da.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.3.1+2badb37d1 for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64

  CheckFunctionExists.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_729da.dir\Debug\\" /Fd"cmTC_729da.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-3rh8on\CheckFunctionExists.c"

LINK : fatal error LNK1104: cannot open file 'pthread.lib' [C:\ngp\bin\CMakeFiles\CMakeScratch\TryCompile-3rh8on\cmTC_729da.vcxproj]

PLEASE HELP !!!

**Comment by Thundros** [comment]
hello?

**Comment by ZoroarkGER** [comment]
got the same issue, hopefully there will be a fix soon.

**Comment by ZoroarkGER** [comment]
> hello?

fixed it!
i simply installed CMake 3.22 and clean copied the repo again, so basically i did everything from the ground up, i then used the anaconda prompt for building the rest instead of the VS dev prompt.

**Comment by Thundros** [comment]
@ZoroarkGER I followed EXACTLY what you said. I still can't find the EXE inside the bin folder I created... even though I THINK it compiled correctly.

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
The C compiler identification is MSVC 19.33.31630.0
The CXX compiler identification is MSVC 19.33.31630.0
The CUDA compiler identification is NVIDIA 11.8.89
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detecting CUDA compiler ABI info
Detecting CUDA compiler ABI info - done
Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/nvcc.exe - skipped
Detecting CUDA compile features
Detecting CUDA compile features - done
Targeting GPU architectures: 75
Module support is disabled.
Version: 9.1.1
Build type: 
Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:118 (message):
  Vulkan was not found.  Neural graphics primitives will still compile and
  run correctly, but DLSS will not be supported.


Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Using Win32 for window creation
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
OptiX headers (optix.h and friends) not found.
CMake Warning at CMakeLists.txt:194 (message):
  OptiX was not found.  Neural graphics primitives will still compile and run
  correctly.  However, SDF training in 'raystab' and 'pathescape' modes will
  be significantly slower.


Found Python: C:/Users/kaori/AppData/Local/Programs/Python/Python310/python.exe (found suitable version "3.10.0", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed 
pybind11 v2.10.1 
Performing Test HAS_MSVC_GL_LTCG
Performing Test HAS_MSVC_GL_LTCG - Success
Configuring done
Generating done

**Comment by ZoroarkGER** [comment]
> @ZoroarkGER I followed EXACTLY what you said. I still can't find the EXE inside the bin folder I created... even though I THINK it compiled correctly.
> 
> Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042. The C compiler identification is MSVC 19.33.31630.0 The CXX compiler identification is MSVC 19.33.31630.0 The CUDA compiler identification is NVIDIA 11.8.89 Detecting C compiler ABI info Detecting C compiler ABI info - done Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped Detecting C compile features Detecting C compile features - done Detecting CXX compiler ABI info Detecting CXX compiler ABI info - done Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped Detecting CXX compile features Detecting CXX compile features - done Detecting CUDA compiler ABI info Detecting CUDA compiler ABI info - done Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/nvcc.exe - skipped Detecting CUDA compile features Detecting CUDA compile features - done Targeting GPU architectures: 75 Module support is disabled. Version: 9.1.1 Build type: Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) CMake Warning at CMakeLists.txt:118 (message): Vulkan was not found. Neural graphics primitives will still compile and run correctly, but DLSS will not be supported.
> 
> Looking for pthread.h Looking for pthread.h - not found Found Threads: TRUE Using Win32 for window creation Found OpenMP_C: -openmp (found version "2.0") Found OpenMP_CXX: -openmp (found version "2.0") Found OpenMP: TRUE (found version "2.0") OptiX headers (optix.h and friends) not found. CMake Warning at CMakeLists.txt:194 (message): OptiX was not found. Neural graphics primitives will still compile and run correctly. However, SDF training in 'raystab' and 'pathescape' modes will be significantly slower.
> 
> Found Python: C:/Users/MYUSERNAME/AppData/Local/Programs/Python/Python310/python.exe (found suitable version "3.10.0", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed pybind11 v2.10.1 Performing Test HAS_MSVC_GL_LTCG Performing Test HAS_MSVC_GL_LTCG - Success Configuring done Generating done

i suggest you follow this tutorial by Bycloudump: https://youtu.be/kq9xlvz73Rg
helped me get this run on my machine, also you can run it on windows 11
